### ISSUE TITLE
Just to clarify one thing

### ISSUE THREAD

**Issue by developerfromjokela** [Esinko/viljami#30]
So is this an web client/application for the Wilma built by Visma?

**Comment by Esinko** [comment]
No this is unofficial and I have no relation to Visma. I'm to related to Visma in any way.

**Comment by Esinko** [comment]
I'll close this issue. If you have anymore questions feel free to reopen.

**Comment by Esinko** [comment]
I want to reopen this because I looked at your profile. 
This project is built to work without servers and with security in mind. I looked at your Wilma Plus app and it seems we've just had a similar idea.
Also this is not a web client. This application is built to be run in an embedded chromium framework, Which is a modified version of chromium disguised as an app that loads .html files as the viewport data and runs Node.js or python (etc.) in the background. 
In it's current form the application is built for desktop, but because it's created using Nw.js (read above) it can easily be ported to run on mobile too.
It also has a "themes" system, where a single .json file creates the whole application view. (I plan on making an editor for this later)
Again, reopen if you have more questions,

**Comment by developerfromjokela** [comment]
Ah you understood me wrong (my bad), I was meaning that this project is made for Wilma service, and Visma developed Wilma 🙂

**Comment by Esinko** [comment]
Yes. This is made for Wilma, the service made by Visma

**Comment by developerfromjokela** [comment]
@Esinko Yes, Wilma Plus is also built around being as secure as it can possibly be. There are servers on some specific things like notifications for exams.

 I've tried notifications on the device, but that ended up draining the battery. 

And Wilma Plus also has built-in RSA encryption, server is used as an public key database. Encryption is done on device.

But it's great that these kind of projects start appearing, last year there weren't any custom made Wilma clients.

**Comment by developerfromjokela** [comment]
But overall, I'm excited to see new Wilma clients being developed 😆

**Comment by Esinko** [comment]
Yeah me too, but luckly Wilma can be put to rest when the new app comes. It's already been paid for an should release and start being used by the city of Helsinki in a few years or so.

**Comment by Esinko** [comment]
Also batteries draining has not been an issue for me as I don't support mobile yet.

**Comment by developerfromjokela** [comment]
@Esinko So is Viljami making Wilma requests from its client? Isn't there popping up CORS errors?

**Comment by developerfromjokela** [comment]
Is the server.js made for making Wilma requests?

**Comment by Esinko** [comment]
First of all look at the 0.2.0 beta branch

**Comment by Esinko** [comment]
And yes. Server.js is for requests

**Comment by Esinko** [comment]
It's an internal webserver to handle proxying requests from the client to Wilma servers

**Comment by Esinko** [comment]
I'm making raw post/get requests. I reverse engineered the api used by the actual Wilma web client.

**Comment by developerfromjokela** [comment]
Ok. I've learned much about the Wilma servers and it's "undocumented APIs" while developing Wilma Plus. So I can help with some requests if you want 😉

**Comment by Esinko** [comment]
Some things don't use the Wilma api tho. So I just get the page and parse the data I want. Take a look in parser.js

**Comment by Esinko** [comment]
Oh yeah that would be nice

**Comment by Esinko** [comment]
I'm not that far in development yet, but if you want make PR with a file explaining what you know, feel free to do that.

**Comment by Esinko** [comment]
I'm gonna go ahead and close this issue now. You can make a new one if you need anything else.

**Comment by developerfromjokela** [comment]
> Some things don't use the Wilma api tho. So I just get the page and parse the data I want. Take a look in parser.js

There's just a small risk that the page can behave differently on some users. I've come across this many times.

**Comment by Esinko** [comment]
Yeah that's correct, but I don't have any other options. It's also as dynamic as possible.
